--create table users(
--id varchar(100) primary key not null,
--username varchar(50) not null,
--avatar_url text,
--avatar_id varchar(100),
--created_at timestamp default now(),
--updated_at timestamp default now()
--);
--alter table users
--add column bio text;

--alter table servers
--drop column server_id;
--create table servers(
--id uuid primary key default uuid_generate_v4(),
--name varchar(25) not null,
--logo text,
--logo_id varchar(100),
--created_by varchar(100) references users(id) on delete cascade,
--created_at timestamp default now(),
--updated_at timestamp default now()
--);
--
--create index concurrently idx_server_name on servers(name);
--alter table servers
--add column banner_colors varchar(20)[],
--add column description text,
--add column private boolean default false;
--ALTER TABLE servers
--ALTER COLUMN banner_colors set DEFAULT '{"#FFFFFF", "#000000"}';
alter table servers
add column banner text default '',
add column banner_id varchar(100) default '';
--
--ALTER TABLE servers
--ALTER COLUMN logo set default '',
--alter column logo_id set default '';

--create table category(
--id uuid primary key default uuid_generate_v4(),
--name varchar(25) not null,
--server_id uuid not null,
--created_by varchar(100) not null,
--created_at timestamp default now(),
--updated_at timestamp default now()
--);
--
--create index concurrently idx_category_server_id on category(server_id);

--create type channel_types as enum('text', 'audio', 'forum');
--
--create table channels(
--id uuid primary key default uuid_generate_v4(),
--name varchar(25) not null,
--channel_type channel_types not null default 'text',
--category_id uuid references category(id) on delete cascade,
--server_id uuid not null references servers(id) on delete cascade,
--created_at timestamp default now(),
--updated_at timestamp default now()
--
--);
--alter table channels
--add column created_by varchar(100) not null references users(id) on delete cascade;
--alter table channels
--add column topic text;
--alter table channels
--alter column topic set default '';
--ALTER TABLE servers ADD COLUMN server_id UUID NOT NULL REFERENCES servers(id) on delete cascade;
--create table members (
--id uuid primary key default uuid_generate_v4(),
--user_id varchar(100) not null references users(id) on delete cascade,
--server_id uuid not null references servers(id) on delete cascade,
--joined_at timestamp default now()
--);
--create index concurrently idx_members_server_id on members(server_id);


--create table messages(
--id uuid primary key default uuid_generate_v4(),
--content text,
--user_id varchar(100) not null references users(id) on delete cascade,
--image_url text,
--image_asset_id varchar(100),
--channel_id uuid not null references channels(id) on delete cascade,
--parent_msg_id uuid,
--created_at timestamp default now(),
--updated_at timestamp default now()
--);

--create index concurrently idx_messages_context on messages(content);
--create index concurrently idx_messages_parent_id on messages(parent_msg_id);

--create table pinned_messages(
--id uuid primary key default uuid_generate_v4(),
--message_id uuid not null references messages(id) on delete cascade,
--channel_id uuid not null references channels(id) on delete cascade,
--pinned_by varchar(100) not null references users(id) on delete cascade,
--created_at timestamp default now(),
--updated_at timestamp default now()
--);

--create index concurrently idx_pin_msg_channel_id on pinned_messages(channel_id);
--create index concurrently idx_pin_msg_pinned_by on pinned_messages(pinned_by);

--create table roles(
--id uuid primary key default uuid_generate_v4(),
--name varchar(25) not null,
--server_id uuid not null references servers(id) on delete cascade,
--color varchar(25) not null,
--created_by varchar(100) not null references users(id) on delete cascade,
--icon text,
--icon_id varchar(100),
--hoist boolean default false,
--mentionable boolean default false,
--created_at timestamp default now(),
--updated_at timestamp default now()
--);

--create table permissions(
--id uuid primary key default uuid_generate_v4(),
--role_id uuid not null references roles(id) on delete cascade,
--list varchar(50)[],
--created_at timestamp default now(),
--updated_at timestamp default now()
--);

--CREATE TABLE "server_profile" (
--id uuid primary key default uuid_generate_v4(),
--	"server_id" uuid not null references servers(id) on delete cascade,
--	"user_id" varchar(100) not null references users(id) on delete cascade,
--	"username" varchar(100) NOT NULL,
--	"avatar" text DEFAULT '' NOT NULL,
--	"avatar_asset_id" varchar(100),
--	"bio" text,
--	created_at timestamp default now(),
--updated_at timestamp default now()
--);

--create table invitations(
--id uuid primary key default uuid_generate_v4(),
--code varchar(25) not null,
--"server_id" uuid not null references servers(id) on delete cascade,
--max_users int default 0,
--created_by varchar(100) not null references users(id) on delete cascade,
--uses int default 0,
--created_at timestamp default now(),
--updated_at timestamp default now()
--);

--create index concurrently idx_invitations_code on invitations(code);
--create index concurrently idx_invitations_server_id on invitations(server_id);

--  ALTER TABLE server_profile ADD COLUMN member_id uuid;
--
--  UPDATE server_profile sp
--  SET member_id = m.id::uuid
--  FROM members m
--  WHERE m.server_id::uuid = sp.server_id AND m.user_id = sp.user_id;
--
--  ALTER TABLE server_profile
--    ALTER COLUMN member_id SET NOT NULL,
--    ADD CONSTRAINT server_profile_member_id_fkey
--      FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE;


-- ALTER TABLE category
--  ADD CONSTRAINT category_server_id_fkey
--  FOREIGN KEY (server_id) REFERENCES servers(id) ON DELETE CASCADE;

--create table user_roles(
--id uuid primary key default uuid_generate_v4(),
--"user_id" varchar(100) not null references users(id) on delete cascade,
--server_id uuid not null references servers(id) on delete cascade,
--role_id uuid not null references roles(id) on delete cascade,
--assigned_by varchar(100) not null references users(id) on delete cascade,
--created_at timestamp default now(),
--updated_at timestamp default now()
--);


--create table friends(
--id uuid primary key default uuid_generate_v4(),
--requester_id varchar(100) not null references users(id) on delete cascade,
--addressee_id  varchar(100) not null references users(id) on delete cascade,
--status        VARCHAR(10) NOT NULL DEFAULT 'pending'
--                CHECK (status IN ('pending', 'accepted', 'blocked')),
-- created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
-- updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
-- CONSTRAINT no_self_friend CHECK (requester_id <> addressee_id),
-- CONSTRAINT unique_pair UNIQUE (requester_id, addressee_id)
--);
--
--CREATE INDEX idx_friends_requester ON friends(requester_id, status);
--CREATE INDEX idx_friends_addressee ON friends(addressee_id, status);

--create table threads (
--   id uuid primary key default uuid_generate_v4(),
--
--   -- the channel where the thread was created
--   channel_id uuid not null references channels(id) on delete cascade,
--
--   name varchar(255),
--   created_by varchar(100) not null references users(id) on delete cascade,
--
--   is_archived boolean not null default false,
--   is_locked boolean not null default false,
--
--   created_at timestamp not null default now(),
--   updated_at timestamp not null default now()
--);
--
--alter table messages
--add column thread_id uuid references threads(id) on delete cascade;
--
--alter table messages
--add constraint message_location_check check (
--      (channel_id is not null and thread_id is null)
--      or
--      (channel_id is null and thread_id is not null)
--   );

--
--ALTER TYPE channel_types ADD VALUE IF NOT EXISTS 'dm';
--ALTER TYPE channel_types ADD VALUE IF NOT EXISTS 'group_dm';


--BEGIN;
--
---- 1. Allow channels to exist without a server.
----    server_id NULL = DM / group DM
----    server_id NOT NULL = normal server channel
--ALTER TABLE channels
--  ALTER COLUMN server_id DROP NOT NULL;
--
---- 2. Allow DM channels to have no name.
----    1:1 DMs usually do not need a channel name.
--ALTER TABLE channels
--  ALTER COLUMN name DROP NOT NULL;
--
---- 3. Add a stable unique key for 1:1 DM conversations.
----    Example dm_key: userA:userB with IDs sorted alphabetically.
--ALTER TABLE channels
--  ADD COLUMN IF NOT EXISTS dm_key text;
--
---- 4. Make sure created_by exists.
----    Your pasted schema shows you already added this column,
----    but this keeps the migration safer if run on another database.
--ALTER TABLE channels
--  ADD COLUMN IF NOT EXISTS created_by varchar(100);
--
--DO $$
--BEGIN
--  IF NOT EXISTS (
--    SELECT 1
--    FROM information_schema.table_constraints
--    WHERE constraint_name = 'channels_created_by_fkey'
--      AND table_name = 'channels'
--  ) THEN
--    ALTER TABLE channels
--      ADD CONSTRAINT channels_created_by_fkey
--      FOREIGN KEY (created_by)
--      REFERENCES users(id)
--      ON DELETE CASCADE;
--  END IF;
--END $$;
--
---- 5. Remove old scope constraint if you tried one before.
--ALTER TABLE channels
--  DROP CONSTRAINT IF EXISTS channels_scope_check;
--
---- 6. Enforce valid channel shapes.
----
---- Valid server channels:
----   server_id IS NOT NULL
----   channel_type IN ('text', 'audio', 'forum')
----   dm_key IS NULL
----
---- Valid 1:1 DM:
----   server_id IS NULL
----   channel_type = 'dm'
----   dm_key IS NOT NULL
----
---- Valid group DM:
----   server_id IS NULL
----   channel_type = 'group_dm'
--ALTER TABLE channels
--  ADD CONSTRAINT channels_scope_check CHECK (
--    (
--      server_id IS NOT NULL
--      AND channel_type IN ('text', 'audio', 'forum')
--      AND dm_key IS NULL
--    )
--    OR
--    (
--      server_id IS NULL
--      AND channel_type = 'dm'
--      AND dm_key IS NOT NULL
--    )
--    OR
--    (
--      server_id IS NULL
--      AND channel_type = 'group_dm'
--    )
--  );
--
---- 7. One unique channel per 1:1 DM pair.
--CREATE UNIQUE INDEX IF NOT EXISTS channels_dm_key_unique
--ON channels(dm_key)
--WHERE channel_type = 'dm' AND dm_key IS NOT NULL;
--
---- 8. Members of DM / group DM channels.
----    Do not use this for normal server channels.
----    Server channel access still comes from your existing members table.
--CREATE TABLE IF NOT EXISTS channel_members (
--  channel_id uuid NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
--  user_id varchar(100) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
--  joined_at timestamp DEFAULT now(),
--
--  PRIMARY KEY (channel_id, user_id)
--);
--
--CREATE INDEX IF NOT EXISTS idx_channel_members_user_id
--ON channel_members(user_id);
--
--CREATE INDEX IF NOT EXISTS idx_channel_members_channel_id
--ON channel_members(channel_id);
--
---- 9. Helpful index for message loading.
--CREATE INDEX IF NOT EXISTS idx_messages_channel_created_at
--ON messages(channel_id, created_at);
--
---- 10. Optional but recommended:
----     Your parent_msg_id exists, but in the pasted schema it does not reference messages(id).
--DO $$
--BEGIN
--  IF NOT EXISTS (
--    SELECT 1
--    FROM information_schema.table_constraints
--    WHERE constraint_name = 'messages_parent_msg_id_fkey'
--      AND table_name = 'messages'
--  ) THEN
--    ALTER TABLE messages
--      ADD CONSTRAINT messages_parent_msg_id_fkey
--      FOREIGN KEY (parent_msg_id)
--      REFERENCES messages(id)
--      ON DELETE SET NULL;
--  END IF;
--END $$;
--
--COMMIT;


--WITH dm_channel AS (
--  INSERT INTO channels (
--    name,
--    channel_type,
--    server_id,
--    dm_key,
--    created_by
--  )
--  VALUES (
--    NULL,
--    'dm',
--    NULL,
--    $3,
--    $1
--  )
--  ON CONFLICT (dm_key) WHERE channel_type = 'dm'
--  DO UPDATE SET dm_key = EXCLUDED.dm_key
--  RETURNING id
--),
--members_insert AS (
--  INSERT INTO channel_members (channel_id, user_id)
--  SELECT id, $1 FROM dm_channel
--  UNION
--  SELECT id, $2 FROM dm_channel
--  ON CONFLICT DO NOTHING
--)
--SELECT id FROM dm_channel;
