export const emojiList = [
  { emoji: '😀', code: 'U+1F600' },
  { emoji: '😂', code: 'U+1F602' },
  { emoji: '❤️', code: 'U+2764' },
  { emoji: '🔥', code: 'U+1F525' },
  { emoji: '😊', code: 'U+1F60A' },
  { emoji: '😍', code: 'U+1F60D' },
  { emoji: '🙏', code: 'U+1F64F' },
  { emoji: '😎', code: 'U+1F60E' },
  { emoji: '😢', code: 'U+1F622' },
  { emoji: '👍', code: 'U+1F44D' },
  { emoji: '✨', code: 'U+2728' },
  { emoji: '🎉', code: 'U+1F389' },
  { emoji: '🌈', code: 'U+1F308' },
  { emoji: '💔', code: 'U+1F494' },
  { emoji: '🥳', code: 'U+1F973' },
  { emoji: '😋', code: 'U+1F60B' },
  { emoji: '😜', code: 'U+1F61C' },
  { emoji: '🤔', code: 'U+1F914' },
  { emoji: '💪', code: 'U+1F4AA' },
  { emoji: '🌟', code: 'U+1F31F' },
  { emoji: '🎂', code: 'U+1F382' },
  { emoji: '🍕', code: 'U+1F355' },
  { emoji: '🍎', code: 'U+1F34E' },
  { emoji: '🚀', code: 'U+1F680' },
  { emoji: '⛄', code: 'U+26C4' },
  { emoji: '☀️', code: 'U+2600' },
  { emoji: '🌙', code: 'U+1F319' },
  { emoji: '⭐', code: 'U+2B50' },
  { emoji: '⚡', code: 'U+26A1' },
  { emoji: '🌍', code: 'U+1F30D' },
  { emoji: '🌹', code: 'U+1F339' },
  { emoji: '🌺', code: 'U+1F33A' },
  { emoji: '🎄', code: 'U+1F384' },
  { emoji: '🎁', code: 'U+1F381' },
  { emoji: '🎈', code: 'U+1F388' },
  { emoji: '🎶', code: 'U+1F3B6' },
  { emoji: '🎸', code: 'U+1F3B8' },
  { emoji: '🎹', code: 'U+1F3B9' },
  { emoji: '🎺', code: 'U+1F3BA' },
  { emoji: '🏀', code: 'U+1F3C0' },
  { emoji: '⚽', code: 'U+26BD' },
  { emoji: '🏆', code: 'U+1F3C6' },
  { emoji: '🏅', code: 'U+1F3C5' },
  { emoji: '🏖️', code: 'U+1F3D6' },
  { emoji: '🚗', code: 'U+1F697' },
  { emoji: '✈️', code: 'U+2708' },
  { emoji: '🚲', code: 'U+1F6B2' },
  { emoji: '⛺', code: 'U+26FA' },
  { emoji: '🗻', code: 'U+1F5FB' },
  { emoji: '🏰', code: 'U+1F3F0' },
  { emoji: '🏝️', code: 'U+1F3DD' },
  { emoji: '🌋', code: 'U+1F30B' },
  { emoji: '🗽', code: 'U+1F5FD' },
  { emoji: '🚂', code: 'U+1F682' },
  { emoji: '🚤', code: 'U+1F6A4' },
  { emoji: '🚉', code: 'U+1F689' },
  { emoji: '🚄', code: 'U+1F684' },
  { emoji: '🚅', code: 'U+1F685' },
  { emoji: '🚜', code: 'U+1F69C' },
  { emoji: '🚛', code: 'U+1F69B' },
  { emoji: '🚕', code: 'U+1F695' },
  { emoji: '🚓', code: 'U+1F693' },
  { emoji: '🛴', code: 'U+1F6F4' },
  { emoji: '🛵', code: 'U+1F6F5' },
  { emoji: '🛶', code: 'U+1F6F6' },
  { emoji: '⛵', code: 'U+26F5' },
  { emoji: '🛰️', code: 'U+1F6F0' },
  { emoji: '🚁', code: 'U+1F681' },
  { emoji: '🛸', code: 'U+1F6F8' },
  { emoji: '🛩️', code: 'U+1F6E9' },
  { emoji: '🚢', code: 'U+1F6A2' },
  { emoji: '⛴️', code: 'U+26F4' },
  { emoji: '🛳️', code: 'U+1F6F3' },
  { emoji: '🚑', code: 'U+1F691' },
  { emoji: '🚒', code: 'U+1F692' },
  { emoji: '🚐', code: 'U+1F690' },
  { emoji: '🚨', code: 'U+1F6A8' },
  { emoji: '🚔', code: 'U+1F694' },
  { emoji: '🚍', code: 'U+1F68D' },
  { emoji: '🚌', code: 'U+1F68C' },
  { emoji: '🚏', code: 'U+1F68F' },
  { emoji: '🏃', code: 'U+1F3C3' },
  { emoji: '🏃‍♀️', code: 'U+1F3C3 U+200D U+2640' },
  { emoji: '🏃‍♂️', code: 'U+1F3C3 U+200D U+2642' },
  { emoji: '🚶', code: 'U+1F6B6' },
  { emoji: '🚶‍♀️', code: 'U+1F6B6 U+200D U+2640' },
  { emoji: '🚶‍♂️', code: 'U+1F6B6 U+200D U+2642' },
  { emoji: '🧍‍♀️', code: 'U+1F9CD U+200D U+2640' },
  { emoji: '🧍‍♂️', code: 'U+1F9CD U+200D U+2642' },
  { emoji: '🧎', code: 'U+1F9CE' },
  { emoji: '🧎‍♀️', code: 'U+1F9CE U+200D U+2640' },
  { emoji: '🧎‍♂️', code: 'U+1F9CE U+200D U+2642' },
] as const;

export const topEmojies = [
  { emoji: '😂', code: 'U+1F602' },
  { emoji: '🔥', code: 'U+1F525' },
  { emoji: '👍', code: 'U+1F44D' },
  { emoji: '🙏', code: 'U+1F64F' },
] as const;

export const discordEmojis = [
  { name: 'joy', emoji: '😂', code: 'U+1F602' },
  { name: 'fire', emoji: '🔥', code: 'U+1F525' },
  { name: 'thumbsup_tone1', emoji: '👍🏻', code: 'U+1F44D U+1F3FB' },
  { name: 'pray_tone1', emoji: '🙏🏻', code: 'U+1F64F U+1F3FB' },
  { name: 'v_tone1', emoji: '✌🏻', code: 'U+270C U+1F3FB' },
  { name: 'kissing_heart', emoji: '😘', code: 'U+1F618' },
  { name: 'smiley', emoji: '😃', code: 'U+1F603' },
  { name: 'grinning', emoji: '😀', code: 'U+1F600' },
  { name: 'black_large_square', emoji: '⬛', code: 'U+2B1B' },
  { name: 'confused', emoji: '😕', code: 'U+1F615' },
] as const;
